### ISSUE TITLE
substr of undefined

### ISSUE THREAD

**Issue by sprockow** [urish/firebase-server#1]
It seems that there is a strong assumption that all firebase requests be of the form:

`{"t":"d","d":{"r":4,"a":"q","b":{"p":"/accounts","h":""}}}`

However, when using the emberfire library, the firebase-server crashes immediately on the first request.

The culprit seems to be this message, which is sent by the library before the first actual request.

`{"t":"d","d":{"r":1,"a":"s","b":{"c":{"sdk.js.0-0-0":1}}}}`

No idea what this request does, but the message payload does not have a property d.b.p

Which causes problems in index.js - line 53

`var path = parsed.d.b.p.substr(1);`

p is undefined, and the server crashes.

I find a workaround by using the following code change:

`var path;
if (parsed.d.b.p) {
   path = parsed.d.b.p.substr(1);
}`

The code is defensive about testing the path variable for a truthy value a few lines later, so this fix doesn't seem to cause any issues. Should I create a pull request, or do you have another suggestion?

**Comment by urish** [comment]
Yes, a PR will be awesome :)

Thanks!

**Comment by aofrozen** [comment]
Better way:

var path; if (typeof parsed.d.b.p !== 'undefined') { path = parsed.d.b.p.substr(1); }

**Comment by urish** [comment]
@sprockow @aofrozen Can you please show me how to reproduce the issue or even better - create a test case for it?

Thanks!

**Comment by sprockow** [comment]
Yeah, its trivial to reproduce using the emberfire adapter. I'm not sure if I can reproduce with the browser-client firebase lib, but I think it should be easy; the emberfire library just wraps the client lib. 

However, I've looked through the source, and found what I believe to the be the source of the  unexpected message format: https://github.com/firebase/firebase-bower/blob/master/firebase-debug.js#L11480. An internal function called _sendConnectStats() will send debugging info over to the firebase service during the initial connection, hence the 
`{"t":"d","d":{"r":1,"a":"s","b":{"c":{"sdk.js.0-0-0":1}}}}`

I'll have some time to look at writing a breaking test this coming week.

**Comment by urish** [comment]
Thanks  @sprockow !

**Comment by urish** [comment]
Apparently, this broke as of firebase client library v2.2.4. Just applied a fix, can you please confirm that it fixes the issue for you as well?

**Comment by sprockow** [comment]
Sorry about the late reply. The latest fix worked. thanks a bunch
