### ISSUE TITLE
Program hangs if closing the server immediately after construction

### ISSUE THREAD

**Issue by p-salido** [urish/firebase-server#107]
Consider this code which creates a firebase server and immediately closes it:

<pre>
var FirebaseServer=require('firebase-server')
const server = new FirebaseServer(5020, 'localhost.firebaseio.com', {})
server.close()
</pre>

If you paste it in a file and run that file with node it'll hang.

A fix is to delay closing:

<pre>
var FirebaseServer=require('firebase-server')
const server = new FirebaseServer(5020, 'localhost.firebaseio.com', {})
setTimeout(function(){
  server.close()
},1)
</pre>

This code quits node when it completes.

`ws` had a similar issue on node 6 but the following code quits when run on node 8.7.0:
<pre>
var Server=require('ws').Server
var iserver=new Server({port:12333})
iserver.close()
</pre>

**Comment by urish** [comment]
Have you found a solution for that?

**Comment by p-salido** [comment]
No, but I haven't looked very hard. I believe I only ran into this issue when writing tests for firebase-server itself.

My guess is the fix would involve marking the server closed in `close()` call and checking that flag in setup/listening code, or possibly in a callback invoked by node's `listen` implementation.

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
