### ISSUE TITLE
Firebase with Android

### ISSUE THREAD

**Issue by robertsteilberg** [urish/firebase-server#113]
I'm trying to run `firebase-server` with an Android project, which requires a `google-services.json` file to tell the Android project how to connect to a Firebase instance. The documentation for `firebase-server` only provides a URL, but `google-services.json` requires an `api_key`among other things. Are there any examples or instructions of a `google-services.json` configured for `firebase-server`?

**Comment by p-salido** [comment]
If leaving the api key blank doesn't work, try a string of `1`s.

**Comment by GabLeRoux** [comment]
Here's a related issue on stackoverflow: https://stackoverflow.com/questions/48193366/required-setup-for-unit-testing-with-firebase-cloud-messaging-under-android

@robertsteilberg  did you manage to get things working?

**Comment by robertsteilberg** [comment]
I was never able to get `firebase-server` running with Android. It seems to me like `firebase-server` isn't that well-maintained anyway, so I decided against testing against it since it may not accurately reflect an actual Firebase instance.

Instead, I created three different (Android flavors)[https://developer.android.com/studio/build/build-variants.html#flavor-dimensions]: `dev` for development, `qa` for running automated tests against, and `prod` for production. I think testing against a real Firebase instance is best since it will always accurately reflect how the app will work in production.

**Comment by urish** [comment]
@puf I'm only doing web stuff with Firebase, but perhaps someone from the team can chime in and shed some light about how you could connect to firebase-server from Android?

**Comment by p-salido** [comment]
There is a massive speed difference between running firebase-server locally and talking to real firebase.

firebase-server supports websocket API and REST API. The REST API needs to be manually enabled, it is off by default. In order to troubleshoot Android issues effectively OP/whoever is having them needs to provide more details on what they are doing and what is happening as a result, both on the client side and the server side.

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
