### ISSUE TITLE
how to  check firebase  from server side

### ISSUE THREAD

**Issue by vigneshindn** [urish/firebase-server#114]
https://github.com/urish/firebase-server#usage-example

thanks in advance, 
i have follow this links and no idea to where/which path i have to insert the code, am new for the technology , so please guide me solve the issue

**Comment by urish** [comment]
Hi @vigneshindn, please try posting your question on [StackOverflow](https://stackoverflow.com), I suggest also to describe what you tried / didn't work, and tag it with the `firebase` tag. Good luck!
