### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by benlakey** [urish/firebase-server#116]
Hello. I saw that there has been work recently to convert this project to typescript.

https://github.com/urish/firebase-server/commit/0aa5f5dc0cd03955795a7776b7ef89fae5de286e
https://github.com/urish/firebase-server/commit/2c45f54f84ed12df6788895bc6b56d0126f3df97
https://github.com/urish/firebase-server/commit/eee960eecf1bfb2e497767eac5031c4bc3f91c4b

Is it your intention to also provide typescript declarations for consumers of this package?

**Comment by urish** [comment]
Hello,

Yes - they should be included starting from the next release.
