### ISSUE TITLE
Priority Queries

### ISSUE THREAD

**Issue by jamestalmage** [urish/firebase-server#12]
Blocker https://github.com/katowulf/mockfirebase/issues/98

(sorry for being short on explanation - I'll flush this out later)

**Comment by jamestalmage** [comment]
OK, 
I did make progress last week but have since been sidetracked

see: [jamestalmage/firebase-server#wip-use-snapshot-branch](https://github.com/jamestalmage/firebase-server/tree/wip-use-snapshot-branch)
and: [jamestalmage/mockfirebase#wip-get-snapshot](https://github.com/jamestalmage/mockfirebase/tree/wip-get-snapshot)

both branches are exploratory / quick hacks. I wouldn't merge any of the changes without careful review. submitted here to help others explore the issue.

As I said, I've gotten a bit sidetracked and might not get back to the issue for a while. If somebody else wants to run with it, I am available to discuss what I think the remaining issues are.

**Comment by urish** [comment]
Have you had a chance to look into it? Perhaps it would be easier now that we have #13 merged...

**Comment by jamestalmage** [comment]
Yes, It definitely should be easier now.
