### ISSUE TITLE
firebase server 

### ISSUE THREAD

**Issue by teeso** [urish/firebase-server#120]
Firebase server is The exact baas that Google provide? May it can be used for a geolocating internal Bluetooth beacon software so i haven't to depend from real firebase services?
Br.
Sincerely
Carlo

I'm evaluating some potential alternative such as deep stream server and rethinkdb (what do You think about this?)

**Comment by urish** [comment]
No, it is not. It does implement the same protocol as the Google Cloud Firebase service, but does is not scalable, does not persist the data to disk, and does not have all of the cloud database features (such as Firebase Authentication), and therefore I would not recommend using it for production scenarios, only as a tool for tests.
