### ISSUE TITLE
Where  does Firebase come from?

### ISSUE THREAD

**Issue by waynew** [urish/firebase-server#121]
In the getting started guide is this code:

```
var client = new Firebase('ws://localhost.firebaseio.test:5000');
client.on('value', function(snap) {
	console.log('Got value: ', snap.val());
});
```

But it's not clear where this magic `Firebase` comes from. I've tried `Firebase = require('firebase')``, and a number of other things. I get responses like `Firebase is not a constructor`. Is this stuff from an old version of things?

I've got these versions in my package.json:

```
 "firebase-admin": "^4.0.2",     
 "firebase-server": "^0.12.0",   
```

Any tips?

**Comment by prescottprue** [comment]
@waynew If I am understanding the question correctly, it comes from requiring `firebase-server`. You are setting up a server that will act as Firebase, but then still connect with the original Firebase library.

[Here is an example](https://github.com/prescottprue/react-redux-firebase/blob/master/test/setup.js#L10) of using `firebase-server` within the tests to test a library which uses Firebase. Here you can see the [default Firebase JS SDK is initialized and used](https://github.com/prescottprue/react-redux-firebase/blob/master/test/setup.js#L63) after the [firebase-server instance is setup](https://github.com/prescottprue/react-redux-firebase/blob/master/test/setup.js#L33-L39).

Hope it helps!

**Comment by urish** [comment]
I have updated the README with an example showing how to use it with the New Firebase JS library.
