### ISSUE TITLE
Firebase | Using in Production for China

### ISSUE THREAD

**Issue by manpreetsingh2011** [urish/firebase-server#122]
Since all Google's services are blocked in China I am trying to use this firebase-server implementation for running an application there.
After trying out several things [listed here](https://firebase.googleblog.com/2015/04/end-to-end-testing-with-firebase-server_16.html), I was able to get my Javascript application to work. 

However, I am running into some serious challenges while trying to doing so:
1. Data is not persistent. In case the server is restarted we loose the data.
2. Authentication services are not there.
3. There is no way to run this in https/wss mode right now. - _I think this would be an easy feature to add, and I can try adding it myself._

Is it possible to have a solution for these problems, especially Pt. 1 & 2?
Is there any other possible way by which I can get access to Firebase services for Chinese audience?

**Comment by urish** [comment]
Unfortunately, firebase-server is not a good solution for this. It is just a testing tool and was never meant to be a production database.

What I would suggest to do is to set up a proxy for the real firebase service - see #56 for some discussion about this. I'm not sure how easy that would be, though, with the new Firebase.
