### ISSUE TITLE
Testing Internet Connectivity & .info/connected

### ISSUE THREAD

**Issue by petermiles** [urish/firebase-server#131]
In an app I'm working on, I'm trying to handle loss of internet connectivity. Yes, firebase does have offline functionality but if they close the browser or tab before they gain connection again, the data won't be persisted.

I've got it to work based on `.info/connected` boolean as outlined in the firebase docs [here](https://firebase.google.com/docs/database/web/offline-capabilities). Turning off/on wi-fi triggers as normal, all good.

Though that led me thinking to Firebase outages. If firebase were to go down, does that boolean in `.info/connected` trigger?

That's what led me to using your package. I spinned up my local firebase server, disconnected, and the modal triggered as if I had lost connection. Though when I start up my server again, the modal doesn't leave. 

I believe this is because the `.info/connected` boolean didn't get turned back to true.

Is this intended? Does firebase-server manage `.info/connected` ?

Thanks!

**Comment by urish** [comment]
Hi Peter, firebase-server doesn't have any specific handling for `.info/connected`. I'm not sure if this even has to be handled at the server level, you can probably learn by looking at the sources of the [client library](https://github.com/firebase/firebase-js-sdk), or opening an issue there and asking this question.

Good luck with your project!
