### ISSUE TITLE
firebase-server not inscribe client events

### ISSUE THREAD

**Issue by steinjonathan** [urish/firebase-server#132]
I'm trying to register and event when firebase client get closed, to know when user close the app or goes to an other site, but it doesn't work with an firebase-server connection.

I figured that event with this code:
`var connectedUsersRef = $this.database().ref('stores/' + $this.currentStore.integration_hash + '/connected_users');
connectedUsersRef.child($this.userKey).onDisconnect().remove();`

And, database() function is:
`$this.database = function() {
	return $this.localService.database();
}`

When "localService" are a firebase instance pointing to official google firebase(online service at https://console.firebase.google.com/), and the client close the app, the onDisconnect() event are fired and the remove() action too. But, when "localService" are a firebase instance pointing to local firebase-server instance, this event are not registered, and when user go out the remove are not fired.

I'am using angularJs on clientside, with official firebase package at https://www.npmjs.com/package/firebase, version "firebase": "^5.5.6".

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
