### ISSUE TITLE
Error compiling test with firebase-server + webpack + mocha

### ISSUE THREAD

**Issue by derekparker** [urish/firebase-server#135]
This issue is with the latest version of `firebase-server` freshly installed.

When I install firebase-server and simply require it in a test file, the resulting test fails to compile with a few errors:

```
 WEBPACK  Failed to compile with 2 error(s)

Error in ./node_modules/firebase-server/node_modules/ws/lib/websocket.js

  Module not found: 'net' in '/<app>/app/node_modules/firebase-server/node_modules/ws/lib'

Error in ./node_modules/firebase-server/node_modules/ws/lib/websocket.js

  Module not found: 'tls' in '/<app>/app/node_modules/firebase-server/node_modules/ws/lib'
```

When I run `npx firebase-server ...` it works just fine, so I'm curious if there is extra setup I must perform in order to get the combination of webpack + mocha + firebase-server to play along nicely together?

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
