### ISSUE TITLE
Add Firebase Cloud Firestore support

### ISSUE THREAD

**Issue by hargwit** [urish/firebase-server#141]
It would be super helpful to add Firebase Cloud Firestore support - currently there is no way of end to end testing a Firestore connected app locally or in CI without hitting the app's main Firestore instance.

**Comment by CoreyKovalik** [comment]
1000% needed

**Comment by Alonski** [comment]
Any plans to support this :)

**Comment by urish** [comment]
Not as part of this project, unfortunately. I don't currently have the bandwidth to maintain cloud Firestore support. I do hope that the Firebase team will eventually create one.

**Comment by Alonski** [comment]
Ok thanks Uri!

**Comment by urish** [comment]
Please use the official Firebase Emulators solution.

**Comment by CoreyKovalik** [comment]
> Please use the official Firebase Emulators solution.

While it's fair to close this issue, it should be known that Firestore emulators are only intended for testing your database read/write access rules.  There is still no support from Google's Firestore product to spin up a local Firestore server and use Firestore database APIs locally.

While Firestore does have benefits over Firebase RTDB, it has drawbacks as well.  My personal opinion would be to recommend only using Firebase RTDB/Firestore for prototypes and prototypes only
