### ISSUE TITLE
Connect to other clients

### ISSUE THREAD

**Issue by shlomo-edu** [urish/firebase-server#162]
If I install this on Windows, can it serve other clients in my local network?
An explanation to my question.
I have some clients that don't want to work with the public firebase.
Does this code enables me to have a local database?
Is it good for production?
Is it simple to install?
Can it run on the same computer with my UI server (the Manager)?
Can I add its instlation to my Manager's install wizard?

**Comment by urish** [comment]
Hi Shlomo,

As the README states, this project is deprecated. It is not good for production.

If you are looking for an open source Firebase alternative, [Supabase](https://supabase.com/) might be a good fit.

Good luck with your project!
