### ISSUE TITLE
Create Contributing.md

### ISSUE THREAD

**Issue by jamestalmage** [urish/firebase-server#17]
Sections: 
- [x] Instructions for cloning / building / testing
- [x] List of build targets
- [x] ~~Roadmap of desired features.~~ reference github issue tracker
- [x] Conditions for an accepted PR (passing tests, etc).
- [x] Recommend open an issue before starting work
- [x] Hints for reverse engineering production firebase: see [here](https://github.com/urish/firebase-server/issues/8#issuecomment-151040925) and [here](https://github.com/urish/firebase-server/issues/8#issuecomment-151103589).

**Comment by urish** [comment]
Great idea! I am going to create the skeleton, feel free to PR with additional instructions as you see fit...

**Comment by urish** [comment]
Also, can you please elaborate about debugging (i.e. `npm run debug`)?

**Comment by jamestalmage** [comment]
Yeah - no coverage, so stack traces are not obfuscated

**Comment by jamestalmage** [comment]
Might make sense to set an Environment variable that sets verbose logging

```js
var loggingEnabled = !!process.env.DEBUG
```

```json
{
  "scripts": {
    "debug": "DEBUG=1 mocha"
  }
}

**Comment by jamestalmage** [comment]
We should add an `npm run watch` target.

```json
 "watch": "mocha -w -r test/mocha-babel.js test/*.spec.js"
```

We may need to go back to using the `--compilers` flag for watch. From the mocha docs:

> transpilers may be used by mapping the file extensions (**for use with --watch**) and the module name 
>*(emphasis added)*

Not sure what the mechanism is there. If it ends up being too complicated we could just set an environment flag when watching and throw.

**Comment by jamestalmage** [comment]
I will look into the watch setup

**Comment by jamestalmage** [comment]
OK, 
It is a bit of a huge Frankenstein PR (I definitely violated the contributing guidelines of one-issue-per-commit), but #24 basically closes this.

I decided that, in leu of providing a Roadmap (which we would have to update frequently), just point people to the open issues.

**Comment by urish** [comment]
Wonderful!
