### ISSUE TITLE
Support `authAnonymously`

### ISSUE THREAD

**Issue by jamestalmage** [urish/firebase-server#20]
Documentation [Here](https://www.firebase.com/docs/web/api/firebase/authanonymously.html) and [Here](https://www.firebase.com/docs/web/guide/login/anonymous.html#section-logging-in)

- [ ] `authAnonymously(cb)`
- [ ] `authAnonymously(cb, {remember: "none"})`
- [ ] `authAnonymously(cb, {remember: "sessionOnly"})`

**Comment by urish** [comment]
:+1:

**Comment by jamestalmage** [comment]
Similar to #19 

This is simply the same as `authWithCustomToken`, where the token contents are:

```js
{
  v: 0,
  iat: TIMESTAMP,
  d: {
    provider: 'anonymous',
    uid: 1bfe46e6-0fd0-43b7-be55-07800c66dfa6
  }
}
```

**Comment by jamestalmage** [comment]
The token contents are retrieved with https GET requests to a separate server, similar to password auth.

Again - this is probably not worth it / low-priority. It's easy enough for users to create these tokens.

It might be worthwhile to create a wrapper for `firebase-token-generator` at some point that simply provides convenience methods for creating stubs of some of these tokens:

```js
wrapper.createAnonymousToken(UID);
wrapper.createFacebookToken(...); 
... etc
```

there is no need for it to be part of this project though.

**Comment by urish** [comment]
Great research work, thanks! 

So let's close #19 and this one?
