### ISSUE TITLE
test.firebase.localhost as host causes error

### ISSUE THREAD

**Issue by nirrek** [urish/firebase-server#3]
Your instructions to use `test.firebase.localhost` causes the Firebase node module to throw an error. Specifically:

```
Error: FIREBASE FATAL ERROR: test.firebase.localhost:5000 is no longer supported.
Please use <YOUR FIREBASE>.firebaseio.com instead
```

If you use `test.firebaseio.com` instead, then it works as intended.

Modules I am using:
```
"firebase": "^2.2.7",
"firebase-server": "^0.1.1"
```

**Comment by urish** [comment]
Thanks for pointing this out! Can you please send a PR for this?

**Comment by softmarshmallow** [comment]
How is this solved?
