### ISSUE TITLE
`createClient()` method

### ISSUE THREAD

**Issue by urish** [urish/firebase-server#30]
A convenience method to quickly create a client Firebase connected to the current server.

A sketch of the proposed solution:

``` javascript
createClient: function() {
    var fbUrl = 'ws://localhost:' + this.port;
    var oldProto = String.prototype.split;
    var Firebase = firebaseCopy();
    var host = url.parse(fbUrl).host;
    String.prototype.split = function () {
        if (this === host) {
            return ['localhost', 'firebaseio', 'test'];
        } else {
            return oldProto.apply(this, arguments);
        }
    };
    var result = new Firebase(fbUrl);
    String.prototype.split = oldProto;
    return result;
}
```

The string prototype trickery overcomes the internal checks in the client library, so we can safely use `localhost` as the target hostname. Hopefully, we will get some support for this from the official library, and will be able to remove this prototyping hacking.

**Comment by urish** [comment]
@jamestalmage thoughts?

**Comment by jamestalmage** [comment]
:+1: I had the same thought

A potential gotcha: I do not think `this === host` will work, since `new String('a') !== 'a'`, and javascript [promotes primitives to objects](http://gfxmonk.net/2010/02/19/javascript-object-promotion.html). Probably needs to be `this.valueOf() === host`

Also, the latest release of `firebase-copy` has a method for hooking require, so there may be a better way:

```js
createClientConstructor: function(firebaseName) {
  var fbUrl = 'ws://localhost:' + this.port;
  var oldProto = String.prototype.split;
  var Firebase = firebaseCopy(function (requestedPath, resolvedPath) {
    if (requestedPath === 'faye-websocket') {
      // return hooked version of faye-websocket where Client ignores input and connects to server
      // ....
      function Client(url) {
         return new OriginalClient(fbUrl);
      }
    } else {
      return require(resolvedPath);
    }
  });

  if (!firebaseName) {
    return Firebase;
  }

  return function(originalUrl) {
    var url = originalUrl.replace('firebaseio.com', 'firebaseio.test');
    if (url.contains('.firebasio.com') === -1) {
      throw new Error('Firebase URL: ' + originalUrl + ' does not match expected firebase name: ' + firebaseName);
    } 
    return new Firebase(url);
  }
},

createClient: function () {
  var Firebase = this.createClientConstructor();
  return new Firebase('https://mock-firebase-server.firebaseio.test');
}
```

The `createConstructor` method would be handy for dependency-injection.

**Comment by ivawzh** [comment]
I am learning Firebase and I wrote some helpers to make Firebase test setup easier:
https://gist.github.com/ivawzh/5b131a314bd0e2d473f85fd17ada2fab
https://gist.github.com/ivawzh/0c1273ddc134e37f7b96cc7cc9b15e2f

**Comment by urish** [comment]
@ivawzh perhaps you can add some comments or a short piece of documentation to explain what you are doing there, and then I would love to link there from the README (or maybe even include it in)?
