### ISSUE TITLE
Standalone file

### ISSUE THREAD

**Issue by whitneyit** [urish/firebase-server#33]
I'm trying to run the server like so

```js
// server.js
var FirebaseServer = require('firebase-server');
new FirebaseServer(5000, 'localhost:5000');
```

Then calling `node server.js`. Is this supported? The connection looks like this:

```js
// app.js
var app = new Firebase('ws://local.firebaseio.com:5000');
```

I ask because when my app connects to that firebase I am receiving the following error:

> WebSocket connection to 'ws://local.firebaseio.com:5000/.ws?v=5' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
15firebase.js:175 WebSocket connection to 'ws://local.firebaseio.com:5000/.ws?v=5' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I have the follwoing in my hosts file:

```
127.0.0.1 local.firebaseio.com
```

And ping shows that it is working.

```sh
$ ping local.firebaseio.com
PING local.firebaseio.com (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.061 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.061 ms

$ ping prod.firebaseio.com
PING prod.firebaseio.com (104.197.110.104) 56(84) bytes of data.
64 bytes from 104.110.197.104.bc.googleusercontent.com (104.197.110.104): icmp_seq=1 ttl=43 time=180 ms
64 bytes from 104.110.197.104.bc.googleusercontent.com (104.197.110.104): icmp_seq=2 ttl=43 time=182 ms
64 bytes from 104.110.197.104.bc.googleusercontent.com (104.197.110.104): icmp_seq=3 ttl=43 time=179 ms
```

**Comment by whitneyit** [comment]
And when I set `export DEBUG=firebase-server` the only log I see is 

> firebase-server Listening for connections on port 5000 +0ms

I don't get any other traffic :disappointed:

**Comment by whitneyit** [comment]
I created an [bare minimum](http://github.com/whitneyit/firebase-server-example) example that demonstrates this problem

**Comment by urish** [comment]
@whitneyit thanks, looking into it

**Comment by urish** [comment]
@whitneyit seems like it has something to do with HSTS enabled on the `firebaseio.com` domain. 

Can you please try switching to use `local.firebaseio.test` instead of `local.firebaseio.com` and let me know if this does the trick?

Don't forget to update your hosts file and point `local.firebaseio.test` to `127.0.0.1`

**Comment by whitneyit** [comment]
I tried that and it no longer errors. However, it no longer connects :(

**Comment by urish** [comment]
Not sure why - here it worked. You can also try connecting to `ws://127.0.1:5000`,  as mentioned in #7

**Comment by firomero** [comment]
it doesn't work to me following the steps...other ideas?
