### ISSUE TITLE
Server won't connect if no default data provided

### ISSUE THREAD

**Issue by jeffbcross** [urish/firebase-server#36]
When I start up the server like this, everything is fine: 

```js
var FirebaseServer = require('firebase-server');
new FirebaseServer(5000, 'test.firebaseio.com', {
    states: {
        CA: 'California',
        AL: 'Alabama',
        KY: 'Kentucky'
    }
});
```

But if I do not pass sample data, I get WebSocket connection errors when I try to connect:

```js
var FirebaseServer = require('firebase-server');
new FirebaseServer(5000, 'test.firebaseio.com');
// WebSocket connection to 'ws://test.firebaseio.com:5000/.ws?v=5' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```

**Comment by jeffbcross** [comment]
NM it still doesn't work when I add the state info :(

**Comment by urish** [comment]
hi @jeffbcross :)

Can you try switching to `test.firebaseio.test` instead? Don't forget to update your hosts file to resolve `test.firebaseio.test` to 127.0.0.1
