### ISSUE TITLE
Frame size of websocket if bigger sent into segment gives error.

### ISSUE THREAD

**Issue by abhishekgahlot** [urish/firebase-server#38]
Hi,

I liked this repo but if the frame size is bigger than what firebase allows. It throws error because json parsing is not possible. I can raise the PR for accumulating buffer until parsing of frame is successful. Looking forward to hear your thoughts.

**Comment by urish** [comment]
Hi, a PR will be appreciated. Also, can you create a small example reproducing the issue?

Thanks!

**Comment by abhishekgahlot** [comment]
@urish Hi again, I don't have working example live online but on firepad if you add a bulk of data immediately to editor frames are divided into parts which you can see in chrome inspector and also given on firebase-debug.js that segments are divided.

**Comment by urish** [comment]
@abhishekgahlot see my comment on the PR - let's try to find a way to reproduce this inside a test case. Possibly by creating a lot of data, perhaps with [`_.times`](https://lodash.com/docs#times)

**Comment by abhishekgahlot** [comment]
@urish Sure thanks!
