### ISSUE TITLE
Angularfire synchronized array

### ISSUE THREAD

**Issue by afallou** [urish/firebase-server#41]
Hi,

Do you think there is anything special that would make firebase-server not work with $firebaseArray?
I have the following array:

```
var arr = $firebaseArray(firebaseRoot.child('users/id123/matches'))
arr.$loaded().then(function(){console.log('loaded')})
```
the data does get sent by firebase-server, since I get the debug output:
```
 firebase-server Client listen users/id123/matches +0ms
  firebase-server Sending message: {"d":{"a":"d","b":{"p":"users/id123/matches","d":{"matchId1":{"people":{"id345":"Firstname"},"tags":{"tag":true}}},"t":null}},"t":"d"} +3ms
  firebase-server Sending message: {"d":{"r":4,"b":{"s":"ok","d":{}}},"t":"d"} +1ms
```
But the ```$loaded``` promise never gets resolved. $firebaseArray is just a wrapper around the usual firebase methods, so I can't quite understand why that would be - any idea?

**Comment by afallou** [comment]
Solved my own problem. For the record: I looked a bit deeper into the AngularFire code, and it turns out that the synchronized array does batch updates - meaning updates from Firebase are held, and the data binding is only updated on the next iteration of the digest loop. Because I'm in a test environment, it means I have to call ```$rootScope.$apply``` myself for ```$loaded``` to be triggered

**Comment by urish** [comment]
Thank you for sharing your findings!
