### ISSUE TITLE
Script using Firebase Server won't end.

### ISSUE THREAD

**Issue by vjancik** [urish/firebase-server#44]
I am using the latest version from npm, and running the basic example from docs.

```javascript
var FirebaseServer = require('firebase-server')
var Firebase = require('firebase')

const instance = new FirebaseServer(5000, 'test.firebaseio.localhost', {
    states: {
        CA: 'California',
        AL: 'Alabama',
        KY: 'Kentucky'
    }
});

var client = new Firebase('ws://test.firebaseio.localhost:5000');
client.once('value', function(snap) {
    console.log('Got value: ', snap.val());
});
```

I even tried calling `instance.close` and `instance._wss.close()` explicitly. But the script still keeps hanging. Do you have some hanging listener left?

Node version `v4.4.2` and `v5.11.0`

**Comment by urish** [comment]
Hi, can you try to run the unit tests (git clone this repo, `npm install`, then `npm test`) and see if the tests hang for you as well?

**Comment by vjancik** [comment]
Hey, I tried it, they don't. But, I see that you are using Mocha, and another colleague of mine was using Firebase-Server in his tests under Mocha too, and he didn't notice the problem.
This is because Mocha kills the process after running the tests and you need to specify:
`--no-exit                               require a clean shutdown of the event loop: mocha will not call process.exit`
to override this behavior. I added the flag to your `test` script in `package.json` and it still exited. Apparently, Istanbul kills forcibly as well.
But running `./node_modules/mocha/bin/_mocha --no-exit` in the root directory of your package successfully leaves the tests hanging (also doesn't respond to `Ctrl+C` unless you use `bin/mocha`, but that's probably a mocha thing).

I hope this helps :)

**Comment by urish** [comment]
Yes, this definitely makes sense. 

Seems like a problem with the underlaying `firebase` library:

http://stackoverflow.com/questions/18046639/node-process-doesnt-exit-after-firebase-once
http://stackoverflow.com/questions/27641764/how-to-destroy-firebase-ref-in-node

**Comment by shaunburdick** [comment]
One workaround I found when using [tape](https://github.com/substack/tape) was to call `test.onFinish(() => process.exit());` at the end. It's not ideal but it seems to get the job done running it both directly and with a test runner.

Example:
```
const test = require('tape');

test('Some test', (t) => {
  // test code
});

test('Another test', (t) => {
  // test code
});

test.onFinish(() => process.exit());
```

**Comment by urish** [comment]
@shaunburdick thanks for sharing your workaround!
