### ISSUE TITLE
Bump up `ws` module as it causes build failures

### ISSUE THREAD

**Issue by ivarprudnikov** [urish/firebase-server#46]
In my case I use your server to be able to run some functional UI tests on Travis and `ws` module causes build failures because of binary addons.

[Newer version of `ws` module dropped binary addons](https://github.com/websockets/ws/releases)

Could you bump up version or at least specify it as peerDependency instead, so that developer could explicitly set the version of ws?

**Comment by urish** [comment]
Hi, can you please send a PR for bumping up the dependency?
