### ISSUE TITLE
Nested security rules not being processed

### ISSUE THREAD

**Issue by seanblezard** [urish/firebase-server#48]
First of all - awesome project.

I have stumbled over this problem. When I define security rules that are nested e.g.

{
  "rules": 
  {
    ".read"   : " auth.service==true ",  
    ".write"  : " auth.service==true ",    

```
"organisations": 
{
  "$uid": 
  {
    ".read"  : "true",
    ".write" : "(auth!=null && data.val() == null) || (newData.child('id') == data.child('id'))"
  }
}
```

  }
}

The rules in the lowest level are not processed by Firebase-Server in tests but are processed when Targaryen is called in tests directly. Is this an issue or am I doing something wrong?

Thanks

**Comment by tech-labellecaisse** [comment]
Hi ! :)

I have the same problem, did you find find a solution ?

Thanks

**Comment by bmcbarron** [comment]
This is a bug with version 2.0.0 of the dependency targaryen, which does rules evaluation. I'm in the process of building a PR to update the dependency to v2.3.3, which will fix this among other rule evaluation bugs.

The newest version of targaryen is 3.0+, but I don't have time at the moment to update firebase-server to the new targaryen API.

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
