### ISSUE TITLE
Not working with firebase@3.0.0

### ISSUE THREAD

**Issue by nfarina** [urish/firebase-server#50]
You probably guessed this already, but wanted to track it somewhere. The new Firebase release includes [some big changes to how the library is initialized](https://firebase.google.com/support/guides/firebase-web#get_a_database_reference_numbered) - instead of using a constructor, they have moved to a "global initialization" strategy. So `new Firebase(...)` is no longer valid. This may also impact the way firebase-server uses an internal instance of the Firebase client itself to perform some tasks.

**Comment by urish** [comment]
Thanks @nfarina ! 

If you have some time to look into it and send a PR for the changes that would be much appreciated!

**Comment by matdehaast** [comment]
@nfarina you have been chosen!

**Comment by nfarina** [comment]
Haha - a dubious honor :) I've made a little bit of progress though and will continue investigating.

**Comment by urish** [comment]
Thanks!

**Comment by nfarina** [comment]
Just wanted to say that your `CONTRIBUTING` guidelines are fantastic. Much appreciated. Makes it easy to dive right in!

**Comment by urish** [comment]
Fixed in 0.6.0
