### ISSUE TITLE
this.Firebase.goOffline is not a function

### ISSUE THREAD

**Issue by dylanjha** [urish/firebase-server#53]
I'm seeing this error when I start firebase server. At first glance this appears to be an error indicating that I am running the new version of the firebase client library (3.0).

I investigated further and found out that in my regular node_modules/ folder in my project directory I have installed firebase 2.4.2, which is my intention.

However, when I dig into `node_modules/firebase-sever/node_modules` I found that firebase-server had installed firebase 3.0.3 incorrectly as one of its dependencies.

```
TypeError: this.Firebase.goOffline is not a function
at Object.FirebaseServer (/Users/dylanjhaveri/code/crowdcast/node_modules/firebase-server/index.js:50:16)
```

packages in my project package.json

```
    "firebase": "2.4.2",
    "firebase-server": "0.5.4",
```

packages in package.json located at `node_modules/firebase-server/package.json`
```
  "dependencies": {
    "cli": "^0.11.1",
    "debug": "^2.2.0",
    "firebase-copy": "0.2.0",
    "jwt-simple": "^0.3.1",
    "lodash": "3.10.1",
    "native-or-bluebird": "1.2.0",
    "targaryen": "2.0.0",
    "ws": "0.8.1"
  },
```

when I look at the folders inside `node_modules/firebase-server/node_modules/` I see:
```
cli/
debug/
firebase/            <<<<  where is this coming from?
firebase-copy/
jwt-simple/
lodash/
native-or-bluebird/
targaryen/
ws/
```

**Comment by dylanjha** [comment]
I discovered this was actually being installed by npm-shrinkwrap. not a firebase-server issue

**Comment by appplumbr** [comment]
I'm getting the same error when using **firebase.goOffline()** below in my Ionic app,

<script src="firebase3.0.3-rc.1.js"></script>
<script src="angularfire.min2.0.1.js"></script>

Any help or hint is appreciated, thanks
