### ISSUE TITLE
goOffline is not a function

### ISSUE THREAD

**Issue by rohillion** [urish/firebase-server#54]
I'm getting this error as the firebase dependency of the firebase-copy library is being downloaded on its last version causing an issue when calling that method on line 50 of firebase-server/index.js.

Verison 2.3.1 was:
Firebase.goOffline()
Now is:
Firebase.database().goOffline()

Cheers!

**Comment by urish** [comment]
Hi, we have this issue to track the update to 3.0.x:

https://github.com/urish/firebase-server/issues/50

**Comment by rohillion** [comment]
Oh sorry about that didn't realised it was closed.
Cheers!
