### ISSUE TITLE
Redirect requests to real database

### ISSUE THREAD

**Issue by johncordeiro** [urish/firebase-server#56]
My company developed an app called U-Report (https://goo.gl/6YuyGW) using firebase. U-Report is a partnership between Ilhasoft and Unicef. It’s a tool that really makes the difference in the people life.

We’re deploying the U-Report platform on **Syria** and they are having problems( using our app. They can’t make login or share their stories, respond polls or anything else that request a connection to Firebase. Syria government or the Google itself **blocks** Firebase requests.

@urish: Is there any way​ using this library to host a firebase server on Amazon (it’s available on Syria) that only redirects the requests to Firebase and respond to clients?

**Comment by urish** [comment]
Hi @johncordeiro, firebase-server isn't the right tool for this job. You would probably need some sort of a proxy. I wrote something like that in the past, you can find the code here:

https://gist.github.com/urish/4a79ad2a48ad68ae6cac6bd0bc4e881c

It is super simple, though, not really documented - in a nutshell, you have to open the network tab and find the Web Socket URL of your real firebase server, then change the code to connect to it. I haven't tested this code with the new Firebase, so some additional tweaks might be required.

Good luck!

**Comment by Ankish** [comment]
@urish @morganchen12 : Is this workaround still valid and any possibility of getting a brief doc on this.
