### ISSUE TITLE
Firebase 3.x

### ISSUE THREAD

**Issue by victoriafrench** [urish/firebase-server#57]
I see from the readme files that the Firebase 2.x api is being used. Does the server support the 3.x api or are there plans to do that? Thanks

**Comment by urish** [comment]
You can connect to this server from Firebase 3.x. 

It works pretty well as long as you just use the Real Time Database component without authentication, storage or the REST API which are not implemented.

Also see #51

**Comment by victoriafrench** [comment]
Thanks. My app uses anonymous authentication, so i'll have to figure out how to work around that.
