### ISSUE TITLE
documentation needed for using with firebase 3.0.0

### ISSUE THREAD

**Issue by donhcd** [urish/firebase-server#58]
This is a super cool project, and I'd really like to use it, but I'm using firebase 3 and the README doesn't explain what support is available for firebase 3.0.0 or how to do anything with it. The top questions for me right now are how do you initialize the app and what kinds of authentication can I use firebase-server to test?

**Comment by urish** [comment]
Hi, you should be able to initialize it simply by providing some API key (shouldn't matter much), and databaseURL:

    firebase.initializeApp({
        apiKey: 'WriteSomethingHere',
        databaseURL: 'ws://127.0.1:5000'
    });

As far as authentication, unfortunately, there is no emulation of the new Firebase auth infrastructure in firebase-server. You can try to investigate it or perhaps ping @johncordeiro who looked into it as part of #56.

**Comment by oliveiragabriel07** [comment]
I found that firebase 3 authentication send requests to "https://www.googleapis.com" endpoint regardless of the defined databaseURL.
I'd like to try reverse engineering firebase web client to figure out how emulate authentication with firebase-server, but I couldn't find a debug version of the firebase 3 web client library. The following repository contains only a minified version: https://github.com/firebase/firebase-bower/

@urish do you have any plans to support emulation of firebase 3 authentication?

**Comment by urish** [comment]
Hi, I don't have any plans to implement emulation of firebase 3 auth, but if anyone would like to give it a go, I will gladly accept a pull request.

**Comment by lgomez** [comment]
I ran into this too. Sharing what worked for me in case it can help anyone:

```javascript
const firebase = require('firebase');

firebase.initializeApp({
  apiKey: 'WriteSomethingHere',
  databaseURL: "ws://127.0.1:5000" // note: ws://localhost:5000 did not work
});
var db = firebase.database();

var ref = db.ref("foo/bar");

ref.once("value", function(snapshot) {
  console.log(snapshot.val());
});

ref.set({
  baz: 'some value',
  xyz: 'another value'
});
```
I'm running this in a node script using the firebase-server that I start through `npm start` which had to be defined like follows:
```json
// ...
"start": "node ./node_modules/.bin/firebase-server",
// ...
```
If I don't use `node ./node_modules/...` and simply do `./node_modules/.bin/firebase-server` I get `env: node\r: No such file or directory` which I think might have to do with the shebang line in the firebase-server scripts but I'm not sure (haven't checked).

Hope this helps.

PS: `firebase-server@0.7.0`, `node@6.3.0` & `osx@10.12.1 Sierra Beta (16B2338c)`

**Comment by iomarcovalente** [comment]
Thanks @lgomez your suggestions were very helpful for me!
I just want to point out, for windows10 users the `npm start` script for starting the server is slightly different: 

`// ...
"start": "node ./node_modules/firebase-server/bin/firebase-server",
// ...`

The script you are using it was triggering me an error, I think it has to do with how windows handles .cmd files
