### ISSUE TITLE
Can't get data from swift app / Can't connect  from Android

### ISSUE THREAD

**Issue by diego1686** [urish/firebase-server#59]
I'm connecting to firebase-server from a swift app and I can't get any data.

This is my server config:

``` javascript
var FirebaseServer = require('firebase-server');

new FirebaseServer(5000, 'test.firebase.localhost', {
   states: {
        CA: 'California',
        AL: 'Alabama',
        KY: 'Kentucky'
    }
});
```

I'm running the firebase server in debug mode, so when the app starts I see the connection on the terminal and the message sent with all the data on the states path:

```
firebase-server New connection from 127.0.0.1:52221 +11s
  firebase-server Sending message: {"d":{"t":"h","d":{"ts":1468957827447,"v":"5","h":"test.firebase.localhost","s":""}},"t":"c"} +0ms
  firebase-server Client message: {"t":"d","d":{"r":1,"a":"s","b":{"c":{"sdk.objc.3-0-1":1}}}} +2ms
  firebase-server Client message: {"t":"d","d":{"r":2,"a":"q","b":{"p":"\/states","h":""}}} +0ms
  firebase-server Client listen states +0ms
  firebase-server Sending message: {"d":{"a":"d","b":{"p":"states","d":{"AL":"Alabama","CA":"California","KY":"Kentucky"},"t":null}},"t":"d"} +1ms
  firebase-server Sending message: {"d":{"r":2,"b":{"s":"ok","d":{}}},"t":"d"} +1ms
```

This is the swift listener. I always get null:

``` swift
let ref = FIRDatabase.database().reference().child("states")
ref.observeEventType(.Value) { (snap) in
      print(snap.value)
 }
```

```
Optional(<null>)
```

On Android I can't even connect to the firebase-server.

Could you help me please? Thanks!

**Comment by urish** [comment]
Hi Diego,

I suggest that you will try to capture the communication between the iOS firebase client and the real firebase server, and compare it with the one that is generated by `firebase-server`. One way to do it would be to set up a super-simple proxy, see #56.

As for Android, not sure why you can't connect - I actually have never used the Android client library for Firebase, so I can't really help here. I guess attaching a debugger is a good starting point and seeing if there are any error messages logged is a good starting point...

**Comment by diego1686** [comment]
Thanks @urish! I did it, these are the results:

- Real firebase server:

```
server {"t":"c","d":{"t":"h","d":{"ts":1468974447051,"v":"5","h":"s-usc1c-nss-136.firebaseio.com:443","s":"uDSnI93Qqk3KoAWJVlGcVb74OVYKZVCc"}}}
client {"t":"d","d":{"r":1,"a":"s","b":{"c":{"sdk.objc.3-0-2":1}}}}
client {"t":"d","d":{"r":2,"a":"q","b":{"p":"\/users","h":""}}}
server {"t":"d","d":{"r":1,"b":{"s":"ok","d":""}}}
server {"t":"d","d":{"b":{"p":"users","d":{"username":"diego"}},"a":"d"}}
server {"t":"d","d":{"r":2,"b":{"s":"ok","d":{}}}}
client {"t":"d","d":{"r":3,"a":"n","b":{"p":"\/users"}}}
server {"t":"d","d":{"r":3,"b":{"s":"ok","d":""}}}
```

- Local one:

```
server {"d":{"t":"h","d":{"ts":1468976255573,"v":"5","h":"test.firebase.localhost","s":""}},"t":"c"}
client {"t":"d","d":{"r":1,"a":"s","b":{"c":{"sdk.objc.3-0-2":1}}}}
client {"t":"d","d":{"r":2,"a":"q","b":{"p":"\/users","h":""}}}
server {"d":{"a":"d","b":{"p":"users","d":{"username":"diego"},"t":null}},"t":"d"}
server {"d":{"r":2,"b":{"s":"ok","d":{}}},"t":"d"}
client {"t":"d","d":{"r":3,"a":"n","b":{"p":"\/users"}}}
```

There are some differences, but honestly I don't understand what it means. Do you?

**Comment by diego1686** [comment]
@urish I indented and re-ordered the json with the query result, and there is just one difference, `"t":null` 

- Real firebase server
```
{
 	"t":"d",
 	"d":{
 		"b":{
 			"p":"users",
 			"d":{
 				"username":"diego"
 			}
 		},
 		"a":"d"
 	}
 }
```

- Local one
```
 {
 	"t":"d",
 	"d":{ 		
 		"b":{
 			"p":"users",
 			"d":{
 				"username":"diego"
 			},
 			"t":null
 		},
 		"a":"d"
 	}
 }
```

**Comment by urish** [comment]
Interesting... Thanks for checking!

Can you try removing the "t":null and see if it does the trick?

I believe it is coming from here:

https://github.com/urish/firebase-server/blob/master/index.js#L124

**Comment by diego1686** [comment]
@urish yes it does! With a simple replace it worked fine

```javascript
clientWs.on('message', function(data) {
		var newData = data.replace(',"t":null', '')
		console.log('server', newData);
		ws.send(newData);
	});
```

I also tested this with the javascript client and it worked too.

So, it should be removed? Sorry, but I don't know how FIrebase internally works... what that "t":null means?  Thanks!

**Comment by urish** [comment]
I have no idea either. But if this does the trick, doesn't break the
JavaScript client and all tests pass, then I guess we're good. Can you
please send a pull request with this fix?

**Comment by diego1686** [comment]
@urish sure!

**Comment by diego1686** [comment]
@urish Hi! Connection from iOS device seems to works fine, but I'm still having problems with Android. I can establish a connection but I get no data. I put a proxy to compare between the local firebase server and the real one and here is the results, the connection seems to be broken:

- Real firebase server
```
conn
server {"t":"c","d":{"t":"h","d":{"ts":1469565483279,"v":"5","h":"s-usc1c-nss-129.firebaseio.com","s":"8539xXU5Ussl8bXC8USZzVrXAr2dhQsb"}}}
client {"d":{"a":"s","r":0,"b":{"c":{"sdk.android.3-0-0":1}}},"t":"d"}
server {"t":"d","d":{"r":0,"b":{"s":"ok","d":""}}}
client {"d":{"a":"q","r":1,"b":{"h":"","p":"test"}},"t":"d"}
server {"t":"d","d":{"b":{"p":"test","d":{"name":"diego"}},"a":"d"}}
server {"t":"d","d":{"r":1,"b":{"s":"ok","d":{}}}}
```

- Local one
```
conn
server {"d":{"t":"h","d":{"ts":1469565720181,"v":"5","h":"test.firebase.localhost","s":""}},"t":"c"}
client {"d":{"a":"s","r":0,"b":{"c":{"sdk.android.3-0-0":1}}},"t":"d"}
client {"d":{"a":"q","r":1,"b":{"h":"","p":"test"}},"t":"d"}
server {"d":{"r":1,"b":{"s":"ok","d":{}}},"t":"d"}
```

What do you think?

**Comment by urish** [comment]
Interesting, it seems like the real server sends the initial data before sending the OK for the command, while we don't.

There is code to do that here:
https://github.com/urish/firebase-server/blob/master/index.js#L184

I suggest debugging the server and trying to see why `pushData` is not being called before sending the OK. Thanks!

**Comment by urish** [comment]
Hi Diego, any progress on this?

**Comment by diego1686** [comment]
Sorry, I couldn't debug it yet. Probably tomorrow will do it

**Comment by houmie** [comment]
@diego1686 

Hi Diego, can you please share how you connected from iOS to the local firebase server? The config isn't clear to me. Many thanks!!!

```
firebaseConfig = Bundle.main.path(forResource: "GoogleService-Info-unittests", ofType: "plist")
FIRApp.configure(with: options)
```

**GoogleService-Info-unittests.plist:**
```
<plist version="1.0">
<dict>
        <key>DATABASE_URL</key>
        <string>ws://localhost.firebaseio.test:5000</string>
</dict>
</plist>
```

**Comment by nyxee** [comment]
where are the starter instructions for working with this firebase-sever and iOS please...

**Comment by nyxee** [comment]
I'm using swift 3 and the provided swift code in the initial question here worked for me.
the problem was with `<string>ws://localhost.firebaseio.test:5000</string>`
and                               `<string>ws://test.localhost.firebaseio:5000</string>`

look at that string carefully and check on what you put in the hosts file.

any ints on how to move from here?

**Comment by urish** [comment]
@puf perhaps someone from the team can help here with how to setup the iOS client library to connect to firebase-server?

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
