### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by krlng** [urish/firebase-server#65]
I just tried to follow your readme, however I only see a blank page saying: "Upgrade Required". I checked, but I use the latest available version via npm. What am I doing wrong?

**Comment by lqlam** [comment]
Me too. :(

**Comment by degroote22** [comment]
It seems that this package is mocking sdk v2. Firebase's SDK is currently at v3.
I'm trying to figure out it aswell, haven't tried but found a fork on some other mocker and it seems updated.
https://github.com/soumak77/mockfirebase

**Comment by pinn3** [comment]
Firebase-server is only a websocket server, not a http-server so it won't serve any webpages.

**Comment by urish** [comment]
Closing, as we now also have a REST API option
