### ISSUE TITLE
How to test auth?

### ISSUE THREAD

**Issue by anotherpit** [urish/firebase-server#69]
I'd like to test my auth related code for Firebase 3 using `firebase-server`. Does `firebase-server` somehow support [Firebase Admin SDK](https://firebase.google.com/docs/admin/setup)? Or is there any way to setup accounts in `firebase-server`? Thanks.

**Comment by Adam-Burke** [comment]
+1. I would like to use the firebase-server as an offline redundancy for certain uses. I do a mix of custom server side token creation and simple login for different users. I dont need auth offline so I could write a modified client to skip auth but is there an easier way to do this? I

**Comment by onetom** [comment]
+1
I was just evaluating Firebase as a potential platform for a project and I was surprised to see no official, locally runnable version of it.

it's a bit scary for me not being able to dev offline... :/
even for the whole google app engine, google provided an api compatible, locally runnable solution...
aws provides local dynamo db too.
(they don't provide local sqs or s3, but luckily there are open source solutions for that too.)

**Comment by urish** [comment]
Unfortunately, I do not have the time required to implement / support the new Firebase Admin SDK, so it won't be implemented as part of this project.
