### ISSUE TITLE
Is firebase server agnostic to the version of the client firebase library being used?

### ISSUE THREAD

**Issue by dylanjha** [urish/firebase-server#70]
The firebase production database works with either the 2.x sdks or the 3.x sdks.

Ideally, this firebase-server package should behave similarly. It shouldn't care which version of the firebase client library is being used.

However, it appears that this package is dependent on a particular `firebase` version. For example:
https://github.com/urish/firebase-server/blob/master/index.js#L73 `firebase.initializeApp` will only work if the 3.x sdk is being used.

Is there a way this could be made the work with both version of firebase client libraries? Or specify in the README the most up-to-date version for 2.x (I think it would be 0.5.4)

**Comment by urish** [comment]
Hi, the server itself should work with 2.x sdk, but is dependent on the 3.x SDK.

The latest version that used firebase 2.x sdk is mentioned in the changelog:

https://github.com/urish/firebase-server/blob/master/CHANGELOG.md#060---2016-06-22

You are invited to send a PR to add it to the README as well, or if you have the time, send a PR to make the code support both versions (but then we also need to find a way to test it against both versions)

**Comment by dylanjha** [comment]
Thank you @urish :)
