### ISSUE TITLE
Support auth with custom tokens

### ISSUE THREAD

**Issue by azell** [urish/firebase-server#8]
I didn't see anything obvious in the server that would trigger authentication callbacks for https://www.firebase.com/docs/web/api/firebase/authwithcustomtoken.html.  Would it be possible to add a list of valid tokens to the FirebaseServer constructor, after the initial dataset?

**Comment by urish** [comment]
@azell sounds like this could be useful, you are invited to add it and send a PR :)

**Comment by jamestalmage** [comment]
I think the best way to do this is as follows:

```js
var server = new FirebaseServer(name, port, ...);

var token = server.createToken({id: 'james', provider:'facebook', /* other data used in rules */});

var ref = new Firebase():

ref.authWithCustomToken(token);
```

That involves figuring out the wireline protocol for authentication tokens. If that proves too difficult, then we could just do:

```js
server.setAuthData({id: 'james', /* ... */}); 
```

That would be easy, but it precludes you from using two clients with alternate login details.

@urish 
Do you have data yet on

**Comment by urish** [comment]
@jamestalmage nothing yet. I will give it a shot after releasing 0.4.0 with your changes from #13 and with #11

**Comment by urish** [comment]
Here we go, wire protocol for auth with custom tokens:

### Request

    {"t":"d","d":{"r":2,"a":"auth","b":{"cred":"TOKEN"}}}

### Response (Success)

    {"t":"d","d":{"r":2,"b":{"s":"ok","d":{"auth":{"provider":"custom","uid":"db409626-910f-4120-bfa6-2d511ab7dca0"},"expires":1447540543}}}}

`d.b.d.auth` can contain additional fields. Actually, it should contain all the fields that appear inside the token.

### Response (Failure)

    {"t":"d","d":{"r":2,"b":{"s":"invalid_token","d":"Could not parse auth token."}}}

**Comment by jamestalmage** [comment]
OK. Want me to work up a PR?

**Comment by urish** [comment]
If you are interested, that'd be awesome :-)

I think that the following API could be added:

    server.setValidAuthTokens([list of valid tokens])

and / or for more complicated cases, when one would want to write a custom handler (e.g. lookup the tokens in a db)

    server.setTokenValidator(function(token) {
        // some logic to determine if the token is valid, returns a promise that will be resolved with
        // auth data, or rejected with a reason why the token is not valid
    })

Thoughts?

**Comment by jamestalmage** [comment]
I think the best option is to use real, signed tokens, and provide convenience methods for creating them:

```js
server.setSecret('someString');

var token = server.generateToken(
  {uid: 'uid', extraData: 3},  
  {admin: false, debug: false, notBefore: 0, expires: new Date(Date.now() + 300)}
);
```

If people want to introduce their own validation mechanism (database lookup, etc), they will need to generate it just like in production. This allows for both an easy shortcut, and full stack integration tests with their own Token Generators. It obviates the need for a custom validator.

**Comment by urish** [comment]
@jamestalmage very good point about using real signed tokens. I am in for the `setSecret()` method (perhaps `setAuthSecret()` will be a little bit more descriptive).

As for generating a token - the user could use `firebase-token-generator` for that (if he uses custom firebase auth, he probably needs that for his production code anyway), so I don't think we should provide a `generateToken()` methods.

**Comment by jamestalmage** [comment]
We may want to wrap `firebase-token-generator` with some convenience methods that set the `iat` claim with a static value, instead of one that changes with the system clock. I'm not sure on that though.

Does the client inspect `iat`/`nbf`/`exp`, or are those values only validated server side?

**Comment by urish** [comment]
Seems like only `iat` is used, for determining which token is more recent:

https://github.com/firebase/firebase-bower/blob/f78ad65e24837274d4756060574e41e2661d49d8/firebase-debug.js#L9003

`nbf` and `exp` are only referenced by [`fb.util.jwt.isValidTimestamp()`](https://github.com/firebase/firebase-bower/blob/f78ad65e24837274d4756060574e41e2661d49d8/firebase-debug.js#L4757), but I could not find any references to that function, and it seems to be omitted from the minified code, hence I assume it is called by some server side / unit test code.

**Comment by jamestalmage** [comment]
I think you are right - no need to wrap `firebase-token-generator`.
We will just decode and inspect the claims.

I am going to provide a few timer methods for the server:

```js
server.setTime(number);
server.setClock(function () {
  // return a number;
});

function defaultClock() {
  return Math.floor((new Date).getTime() / 1000);
}
```

The server will use those to validate `expired` and `notBefore`.

**Comment by urish** [comment]
Good idea! I think we better namespace all of those method under `server.auth` or `server.customAuth` (e.g. `server.auth.setTime()`, `server.auth.setSecret()`, etc.). Perhaps they can also live in a different module to make the code more readable...

Uri

**Comment by jamestalmage** [comment]
The timer probably has implications outside of auth. (server value)

**Comment by urish** [comment]
Good point!

I don't think we support it ATM, but it is a good point to have in mind when designing the API

**Comment by jamestalmage** [comment]
@urish 
I've got a decent start on this.

How thoroughly have you tested the error responses?  Here are the possible failure modes I can think of:

1. Invalid JWT - it simply is not formatted correctly
2. Invalid Signature - wrong secret
3. Too Early - the server time is before `notBefore`
4. Too Late - the server time is after `expires`
5. No `uid` property - `firebase-token-generator` the docs say you are required to provide a `uid` as part of authData. That is a firebase specific requirement (it will not be validated by a generic JWT library like `jwt-simple`).
6. No `iat` property - I do not actually know if this is required, but the token generator definitely automatically adds it (it is the time the token was created).


In general, how are you reverse engineering the wire protocol? Have you written some specific test harness that hacks the Firebase prototype, or are you just using Wireshark? I'd assume the former, but I think it would be good if you could share that somewhere in the codebase here.

**Comment by jamestalmage** [comment]
Also,
We need to figure out what happens when a token expires. Are you just switched to "unauthenticated" mode? Is a message sent to idle clients? How is `ref.onAuth()` triggered as your token expires?

**Comment by azell** [comment]
I believe that adding ```Firebase.enableLogging(true);``` will enable diagnostic logging including HTTPS traffic.  Ref: http://stackoverflow.com/questions/22419073/how-do-i-turn-on-logging-in-the-firebase-javascript-client.

**Comment by urish** [comment]
Hi @jamestalmage, initially, I used `Firebase.enableLogging(true);`. 

However, now I am using a slightly different approach which I found much more convenient: Open the Network Tab in Chrome Dev Tools, enable filtering and then filter by web sockets (by clicking WS). Finally, select the connection you are interested in and click on Frames to see the entire chat between the client and the server:

![image](https://cloud.githubusercontent.com/assets/892318/10727494/fbaed198-7be2-11e5-950e-b8a2939ee2ea.png)

You can match requests and responses by looking at the `d.r` parameter, which is the sequential request id.

**Comment by urish** [comment]
From what I have seen in the client code, the client itself requires the `iat` parameter to be present, otherwise, it considers the token to be invalid:

https://github.com/firebase/firebase-bower/blob/f78ad65e24837274d4756060574e41e2661d49d8/firebase-debug.js#L4784

While I think that emulating the exact server behavior on errors will be nice to have, I think that even if we use slightly different error strings, this feature will be no less useful to most of the users...

**Comment by jamestalmage** [comment]
> I think that even if we use slightly different error strings, this feature will be no less useful to most of the users

You are probably right. I don't think Firebase documents error codes anyways.
