### ISSUE TITLE
CLI fails to start

### ISSUE THREAD

**Issue by eahlberg** [urish/firebase-server#80]
After upgrading to version 0.9.0 I get the following error when trying to start the CLI on MacOS Sierra with node 6.5.0:

```
$ node_modules/.bin/firebase-server -p 5555
env: node\r: No such file or directory
```

I've looked into this a bit, and my guess is that it fails due to `\r` characters in the file. If I convert the file to unix format using e.g. `dos2unix` it works fine again. Is it possible to fix this by e.g. republishing an updated build of the package? I'm not really well versed in how the npm registry works.

**Comment by urish** [comment]
Fixed in 0.9.1
