### ISSUE TITLE
How to connect via Swift?

### ISSUE THREAD

**Issue by houmie** [urish/firebase-server#85]
Is there any chance to explain how to connect to this via Swift on iOS?  The way Firebase currently works is that it requires a Google-Service-Info.plist, which predefines all the necessary fields to connect to the remote server. I’m unsure about how to provide that for the local database.

Any help would be highly appreciated,
Houman

**Comment by houmie** [comment]
In other words how to I connect in Swift via ```FIRApp.configure(with: options)``` to the local firebase-server?

```
var firebaseConfig: String!
        if isRunningTests() {
            // unit test server (idealy local)
            firebaseConfig = Bundle.main.path(forResource: "GoogleService-Info-tests", ofType: "plist")
        } else {
            #if DEBUG
                // staging server
                firebaseConfig = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist")
            #else
                // production server
                firebaseConfig = Bundle.main.path(forResource: "GoogleService-Info-prod", ofType: "plist")
            #endif
        }
        
        guard let options = FIROptions(contentsOfFile: firebaseConfig) else {
            fatalError("Invalid Firebase configuration file.")
        }
        
        FIRApp.configure(with: options)
        FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
        FIRDatabase.database().persistenceEnabled = true
```

**Comment by mcdonamp** [comment]
You can use the `init!(googleAppID: String!, bundleID: String!, gcmSenderID GCMSenderID: String!, apiKey APIKey: String!, clientID: String!, trackingID: String!, androidClientID: String!, databaseURL: String!, storageBucket: String!, deepLinkURLScheme: String!)` method and pass in AppId, bundleId, SenderID from a real app, and then databaseURL, which can be a local URL. You should be able to pass `nil` into the others and be fine.

**Comment by houmie** [comment]
Thanks that works.
