### ISSUE TITLE
Unexpected format of the auth when talking to Android app

### ISSUE THREAD

**Issue by dotdoom** [urish/firebase-server#88]
Was using firebase-server to test Android app for about 2 months now but not with the rules file (`-r`), i.e. every operation was allowed by default.
Today I wanted to improve my setup a bit and got stuck with authentication. Looks like the auth token coming from Android is not quite what firebase-server expects:

```
  firebase-server:token-validator decode(token: "<redacted>", secret: null) =>
{
  "iss":"https://securetoken.google.com/<app-name>",
  "provider_id":"anonymous",
  "aud":"<app-name>",
  "auth_time":1494740845,
  "user_id":"1p1VFLRdM2azwFqDNkW30i54QSU2",
  "sub":"1p1VFLRdM2azwFqDNkW30i54QSU2",
  "iat":1494740845,
  "exp":1494744445,
  "firebase":{"identities":{},"sign_in_provider":"anonymous"}
} +2ms
```
(indentation modified into a human readable form)

Replacing [line 116](https://github.com/urish/firebase-server/blob/0.10.0/index.js#L116) in `firebase-server/index.js`:

```javascript
data = server._tokenValidator.decode(authToken).d;
```

with

```javascript
data = {uid: server._tokenValidator.decode(authToken).user_id};
```

makes this token work indeed, but this doesn't seem like a right thing to do, and I don't have a JavaScript app with me to compare the formats. What do you think?

**Comment by urish** [comment]
The authorization part is actually handled by [targaryen](https://github.com/goldibex/targaryen), so I think you can open an issue there and see if they can check for either `uid` or `user_id` inside the auth token (if it makes sense to them)

**Comment by dotdoom** [comment]
I see, but the problem is that `firebase-server` cuts out any information in the token by only supplying `token.d` to targaryen. In the Android sample above, the data is stored in the "root" of object and `token.d` is empty. Do you by chance have an example of JavaScript client token payload for me to compare?

**Comment by dotdoom** [comment]
After looking at [Create Custom Tokens](https://firebase.google.com/docs/auth/admin/create-custom-tokens) firebase documentation I can confirm that the field should read `uid` instead of `user_id`. I'll ask targaryen developers to see if they can process the latter as the former, but this alone will not solve the `.d` issue from above.
