### ISSUE TITLE
Wire protocol does not match Firebase server

### ISSUE THREAD

**Issue by azell** [urish/firebase-server#9]
With debug logging turned on:

*Firebase*
Sun Aug 16 23:32:08 PDT 2015 [DEBUG] WebSocket: ws_1 - handleIncomingFrame complete frame: {d={r=1, b={s=ok, **d={}**}}, t=d}
Sun Aug 16 23:32:08 PDT 2015 [DEBUG] Connection: conn_1 - received data message: {r=1, b={s=ok, **d={}**}}

*firebase-server*
Sun Aug 16 23:15:19 PDT 2015 [DEBUG] WebSocket: ws_0 - handleIncomingFrame complete frame: {d={r=1, b={s=ok, **d=**}}, t=d}
Sun Aug 16 23:15:19 PDT 2015 [DEBUG] Connection: conn_0 - received data message: {r=1, b={s=ok, **d=**}}

I believe that "d" should be an empty hash instead of the empty string.

**Comment by azell** [comment]
Some additional context: using the Firebase Java SDK and https://www.firebase.com/docs/android/api/#query_addListenerForSingleValueEvent.  The current firebase-server available through npm causes the following error in the Firebase client:

Sun Aug 16 23:15:19 PDT 2015 [DEBUG] Connection: conn_0 - Failed to parse server message: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map

**Comment by urish** [comment]
@azell hi, thank you for pointing out this issue! Can you please send a PR with a proposed fix?

Thanks!

**Comment by urish** [comment]
Released as 0.3.1
