### ISSUE TITLE
firebase-admin

### ISSUE THREAD

**Issue by Gabrn** [urish/firebase-server#94]
Is it possible to use firebase-admin with firebase-server and if it is what credentials do I pass?

**Comment by azaslavsky** [comment]
Any word on this?  I've been wondering the same thing.

**Comment by GabiNir** [comment]
I managed to make it work but I cheated a little.

This is how I initialized firebaseAdmin:

**Comment by genkobar** [comment]
@GabiNir, any chance you know how to make this mock credential in an iOS app using Firebase?

**Comment by GabiNir** [comment]
@genkobar sorry but I don't really follow, are you trying to use firebase server in an iOS app?

**Comment by genkobar** [comment]
@GabiNir Oh, sorry, I conflated this FirebaseAdmin project with the official Firebase library FirebaseAuth. I'm trying test an iOS app against `firebase-server` instead of actual Firebase, but I was having trouble with tests that require an authenticated user.

**Comment by GabiNir** [comment]
@genkobar you can see my previous post about how to work with firebase-server and authenticated users (it doesn't work properly out of the box because for example authenticateWithCustomToken is forcing you to use RS256 and not HS256 which is used by firebase-server). Another thing you might want to do is download your rule file every time you run your tests to keep it in track with how the rules are in your production and not run out of sync. Here is an example:

```
const server = new FirebaseServer(5000, 'localhost.firebaseio.test');
    const rules = (await axios.get(
      'https://<firebase_proj>.firebaseio.com/.settings/rules.json?auth=<your_auth>'
    )).data;
    server.setRules(rules);
```

**Comment by calclavia** [comment]
Using @GabiNir's method, I seem to be getting this error:

```
     Error: Invalid value for config firebase.databaseURL: ws://127.0.1:5000
```

Anyone know a solution to hack around this?

**Comment by GabiNir** [comment]
@calclavia You can set an alias in etc/hosts in your local computer for localhost as `local.firebaseio.test`
and then just use this string like this: `local.firebaseio.test:5000`

**Comment by calclavia** [comment]
@GabiNir Is there a way to do that without hosts (so this can be easily run on a CI)? Seems like there's a way to hack the websocket and trick it to connect to localhost, but I haven't got that working with firebase-admin...

https://github.com/urish/firebase-server/blob/ce6db9414e0ae515e0fd8b2b226cb5a91631b0d4/test/server.spec.js#L22

**Comment by azaslavsky** [comment]
@calclavia Not that it necessarily resolves your problem, but as far as I know, all of the most popular SaaS CI solutions allow you to configure your `etc/hosts` fairly easily.  Some docs that might help:

[Circle CI](https://circleci.com/docs/1.0/configuration/#hosts)
[Travis CI](https://docs.travis-ci.com/user/hosts)

**Comment by urish** [comment]
@calclavia see this: firebase/firebase-js-sdk#426, seems like you will just be able to use ws://localhost soon

**Comment by urish** [comment]
also, regarding the original question - see #81
