### ISSUE TITLE
Daemonization

### ISSUE THREAD

**Issue by p-salido** [urish/firebase-server#96]
Am I seeing it correctly that firebase-server does not have a daemonization option? Been battling backgrounding in CircleCI for a while.

**Comment by urish** [comment]
correct, it does not have it. You are invited to send a PR and add this option to the [cli](https://github.com/urish/firebase-server/blob/master/bin/firebase-server.js), also, please document it in the README file.

**Comment by p-salido** [comment]
The workaround right now is 

<pre>
./firebase-server/bin/firebase-server & <your ci command>
</pre>

which is not 100% pretty but does work.

**Comment by p-salido** [comment]
Looks like https://www.npmjs.com/package/daemon and https://www.npmjs.com/package/daemonize2 are contenders with daemon seemingly being a better choice.

**Comment by urish** [comment]
Let's go with daemon then :-)

Uri
