### ISSUE TITLE
Getting Started.

### ISSUE THREAD

**Issue by nyxee** [urish/firebase-server#97]
Hello.

1. am I supposed to run `npm install --save-dev firebase-server` as root or from a specific folder?? I saw some files created when i ran from my home folder.

2. what do u mean by **run the server below**

```js
var FirebaseServer = require('firebase-server');

new FirebaseServer(5000, 'localhost.firebaseio.test', {
	states: {
		CA: 'California',
		AL: 'Alabama',
		KY: 'Kentucky'
	}
});
```
I have managed to run a local Parse serve using npm and nodeJS. thats all i've ever done with nodeJS but i'm familiar with JavaScript. 

Thanks for any help please.

**Comment by urish** [comment]
If you just need to run the server from the command line, you can install it globally:

`npm install --global firebase-server`

then run it using the CLI:

`firebase-server -p 5555`

for more usage examples, see [here](https://github.com/urish/firebase-server#command-line-interface)

**Comment by nyxee** [comment]
ok. where did it install with the `--save-dev` option.

I realized that when i put the JavaScript code in a file called *firebase1.js* then put it in the same folde as the one containing the codes downloaded in the directory i had run you `npm install..` from, I managed to get something running on *port 5000 * without running the  `firebase-server -p 5555` line.

Thanks a lot for your prompt help.

**Comment by urish** [comment]
With --save-dev it installs it inside node_modules in the current directory (or nearest parent directory that has a package.json file
